### ISSUE TITLE
CALF Calibration & CALF Calibration GCN Benchmark code error

### ISSUE THREAD

**Issue by rorybunker** [SoccerNet/sn-spotting#11]
While trying to run the benchmark CALF_Calibration_GCN code as per the instructions in this repository, I receive the following error:

```
Traceback (most recent call last):
  File "src/main.py", line 10, in <module>
    from dataset import SoccerNetClips, SoccerNetClipsTesting, collateGCN, collateGCNTesting
  File "/work2/b_rory/work/SoccerNet/sn-spotting/Benchmarks/CALF_Calibration_GCN/src/dataset.py", line 24, in <module>
    from torch_geometric.data import Data
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 7, in <module>
    from .lightning_datamodule import (
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/data/lightning_datamodule.py", line 8, in <module>
    from torch_geometric.loader.dataloader import DataLoader
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/loader/__init__.py", line 15, in <module>
    from .dynamic_batch_sampler import DynamicBatchSampler
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/loader/dynamic_batch_sampler.py", line 9, in <module>
    class DynamicBatchSampler(torch.utils.data.sampler.Sampler[List[int]]):
TypeError: 'type' object is not subscriptable
```

Could you please advise how I can resolve this?

**Comment by rorybunker** [comment]
I obtain the same error when running the benchmark CALF_Calibration code:

```
Traceback (most recent call last):
  File "src/main.py", line 10, in <module>
    from dataset import SoccerNetClips, SoccerNetClipsTesting
  File "/work2/b_rory/work/SoccerNet/sn-spotting/Benchmarks/CALF_Calibration/src/dataset.py", line 24, in <module>
    from torch_geometric.data import Data
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 7, in <module>
    from .lightning_datamodule import (
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/data/lightning_datamodule.py", line 8, in <module>
    from torch_geometric.loader.dataloader import DataLoader
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/loader/__init__.py", line 15, in <module>
    from .dynamic_batch_sampler import DynamicBatchSampler
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/loader/dynamic_batch_sampler.py", line 9, in <module>
    class DynamicBatchSampler(torch.utils.data.sampler.Sampler[List[int]]):
TypeError: 'type' object is not subscriptable
```

**Comment by cioppaanthony** [comment]
Hi @rorybunker,

Could you please share the versions of python, torch, torchvision, cudatoolkit, cv2, and torch_geometric you are using ?

Thank you.

**Comment by rorybunker** [comment]
Python 3.8.13
torch 1.6.0
torchvision 0.7.0
cv2 4.5.4

If I run `cat /usr/local/cuda/version.txt`, I get CUDA Version 10.0.130
But if I run `python -c "import torch; print(torch.version.cuda)"`, I get 10.1

Actually, I am unable to even import torch_geometric — if I do so, I get that same error: 
```
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 7, in <module>
    from .lightning_datamodule import (
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/data/lightning_datamodule.py", line 8, in <module>
    from torch_geometric.loader.dataloader import DataLoader
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/loader/__init__.py", line 15, in <module>
    from .dynamic_batch_sampler import DynamicBatchSampler
  File "/home/b_rory/workspace2/virtualenvs/venv/envs/CALF-pytorch/lib/python3.8/site-packages/torch_geometric/loader/dynamic_batch_sampler.py", line 9, in <module>
    class DynamicBatchSampler(torch.utils.data.sampler.Sampler[List[int]]):
TypeError: 'type' object is not subscriptable
```

**Comment by cioppaanthony** [comment]
Did you install torch_geometric with these lines ?
```
TORCH=1.6.0
CUDA=cu101
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
pip install torch-geometric
```

Does  the `pip freeze` commande give you any information about the version of torch_geometric installed?

Maybe there is simply a mismatch between the CUDA versions or it is not the right version of torch-geometric.
Some people also had errors when not working on the exact same torch_geometric version.

I will check which version I got installed as well.

**Comment by cioppaanthony** [comment]
Ok thank you. 

Unfortunatly, I can't find my docker image right now, I will ask Silvio if he still has it.
But by the release date of pytorch_geometric, it seems that the version was 1.6.3 (or 1.7.0) when we worked on that project.
Could you please try to install one of these version and import the library?
`pip install torch-geometric==1.6.3`

I will update the README once we find the right library version. Sorry about that.

**Comment by SilvioGiancola** [comment]
Hi @rorybunker, I believe your issue originates from a newer version of torch-geometric>=2.0.0. Please let us know if the issue persists with older versions of torch-geometric, as suggested by @cioppaanthony

**Comment by rorybunker** [comment]
Hi @SilvioGiancola, @cioppaanthony, thanks for your help. This error seems to now be resolved by installing torch geometric using `pip install torch-geometric==1.6.3` rather than `pip install torch-geometric`.
